import {ROLES,STATUS,ACUITIES,SYMPTOMS,ALERTS,PROTOCOL,APP_TIME_ZONE,today,ageMonths,classify} from '/shared/domain.js';
const $=s=>document.querySelector(s);
const state={user:null,csrf:'',config:{},students:[],schools:[],page:'inicio',query:'',filter:'all',detail:null,wizard:null,step:0,help:false,practice:0};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const d=date=>date?new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}).format(new Date(date+'T12:00:00Z')):'—';
const age=dob=>Number.isFinite(ageMonths(dob))?Math.floor(ageMonths(dob)/12)+' años':'—';
const school=id=>state.schools.find(s=>s.id===id)?.name||'Escuela';
const has=(...roles)=>roles.includes(state.user?.role);
const status=p=>`<span class="badge ${esc(STATUS[p.status]?.tone||'gray')}">${esc(STATUS[p.status]?.label||'Sin tamizaje')}</span>`;
const icon=(name)=>{const paths={home:'<path d="m3 10 9-7 9 7v10H3Z"/><path d="M9 20v-7h6v7"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m3 10v-3a6 6 0 0 0-2-4"/>',eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>',heart:'<path d="M20 5a5 5 0 0 0-8 1 5 5 0 0 0-8-1c-6 6 8 15 8 15S26 11 20 5Z"/>',glasses:'<circle cx="6" cy="14" r="4"/><circle cx="18" cy="14" r="4"/><path d="M10 14h4M2 14l2-9h3m15 9-2-9h-3"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',book:'<path d="M12 5C8 2 3 3 3 3v16s5-1 9 2c4-3 9-2 9-2V3s-5-1-9 2Zm0 0v16"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',plus:'<path d="M12 5v14M5 12h14"/>',arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',search:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',logout:'<path d="M9 4H4v16h5m5-13 5 5-5 5m-5-5h10"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>',check:'<path d="m5 12 4 4L19 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5"/>',school:'<path d="m2 9 10-6 10 6M4 9v12h16V9M9 21v-7h6v7"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',print:'<path d="M6 8V3h12v5M6 18H3V8h18v10h-3M6 14h12v7H6Z"/>',edit:'<path d="m15 4 5 5-11 11H4v-5ZM13 6l5 5"/>',shield:'<path d="M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6Zm-4 10 3 3 5-6"/>'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.eye}</svg>`;};
const btn=(text,action,extra='',kind='')=>`<button class="btn ${kind}" data-action="${action}" ${extra}>${text}</button>`;
const navItems=[['inicio','Inicio','home'],['alumnos','Alumnos','users'],['tamizaje','Tamizaje','eye'],['consultas','Consultas','heart'],['anteojos','Anteojos','glasses'],['seguimiento','Seguimiento','clock'],['recursos','Recursos','book'],['admin','Administración','settings']];
function allowedNav(){return navItems.filter(([key])=>{if(key==='admin')return has('admin');if(key==='consultas')return has('admin','clinician');if(key==='anteojos')return has('admin','clinician','workshop');if(['alumnos','tamizaje','seguimiento'].includes(key))return !has('workshop');return true;});}
async function api(path,options={}){
  const headers={'X-HV-Request':'1',...(options.body?{'Content-Type':'application/json'}:{}),...(state.csrf?{'X-CSRF-Token':state.csrf}:{})};
  let response;try{response=await fetch('/api'+path,{credentials:'same-origin',...options,signal:AbortSignal.timeout(15000),headers:{...headers,...options.headers},body:options.body?JSON.stringify(options.body):undefined});}catch{throw Error('No pudimos confirmar la respuesta del servidor. Conservá el formulario y revisá la ficha antes de volver a guardar.');}
  let data;try{data=await response.json();}catch{throw Error('El servidor de la aplicación no está disponible. Avisá al equipo coordinador.');}if(!response.ok){if(response.status===401&&state.user){state.user=null;state.students=[];state.schools=[];state.detail=null;state.wizard=null;$('#modal').close();render();}throw Error(data.error||'No pudimos completar la acción.');}return data;
}
function notify(message){$('#notice').textContent=message;clearTimeout(state.timer);state.timer=setTimeout(()=>$('#notice').textContent='',4500);}
function brand(){return `<a href="#inicio" class="brand"><img src="/assets/favicon.svg" alt="" class="brand-mark"><span class="brand-name">Haciendo la<br>Vista Gorda<small>Salud visual escolar</small></span></a>`;}
async function refresh(){const out=await api('/overview');state.students=out.students;state.schools=out.schools;}
function navigate(page){if(location.hash==='#'+page){state.page=page;render();}else location.hash=page;}
function heading(title,sub,action=''){return `<div class="page-heading"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;}
function empty(title,body,action=''){return `<div class="empty">${icon('eye')}<h3>${title}</h3><p>${body}</p>${action}</div>`;}
function render(){
  if(!state.user){$('#app').innerHTML=login();return;}
  if(!allowedNav().some(x=>x[0]===state.page))state.page='inicio';
  const label=navItems.find(x=>x[0]===state.page)?.[1]||'Inicio';
  $('#app').innerHTML=`<div class="layout"><aside class="sidebar" aria-label="Navegación principal">${brand()}<p class="nav-label">Mi espacio de trabajo</p><nav class="nav">${allowedNav().map(([key,title,ic])=>`<a href="#${key}" class="${state.page===key?'active':''}" ${state.page===key?'aria-current="page"':''}>${icon(ic)}${title}</a>`).join('')}</nav><a class="btn secondary" href="/ecosistema.html">Aplicaciones VinTracker</a><div class="side-note"><span class="seed">Ver bien también<br>es aprender mejor.</span>Un proyecto de estudiantes<br>de Medicina · UNCAus<br><small>Versión 1.2.1</small></div></aside><div class="workspace"><header class="topbar"><button class="icon-btn menu-btn" aria-label="Abrir menú" data-action="menu">${icon('menu')}</button><div class="crumb">Salud visual ${icon('arrow')} <strong>${label}</strong></div><div class="top-actions"><div class="avatar" aria-hidden="true">${esc(state.user.name.split(' ').map(x=>x[0]).slice(0,2).join(''))}</div><div class="user-details"><div class="user-name">${esc(state.user.name)}</div><div class="user-role">${esc(ROLES[state.user.role])}</div></div><button class="icon-btn" data-action="password" aria-label="Cambiar mi contraseña">${icon('settings')}</button><button class="icon-btn" data-action="logout" aria-label="Cerrar sesión">${icon('logout')}</button></div></header>${state.config.demo?'<div class="demo-bar"><span><strong>Demostración</strong> · Todos los alumnos son ficticios.</span><button data-action="roles">Cambiar perfil</button></div>':''}${!navigator.onLine?'<div class="network-warning">Sin conexión. La app necesita comunicarse con el servidor para guardar.</div>':''}<main id="main" class="page" tabindex="-1">${renderPage()}</main></div></div><button class="mascot-launch" data-action="help" aria-label="${state.help?'Cerrar':'Abrir'} ayuda de Lupi" aria-expanded="${state.help}"><img src="/assets/lupi.png" alt="Lupi, mascota con anteojos"></button>${state.help?help():''}`;
  if(state.page==='admin')loadAdmin();
}
function login(){return `<div class="login"><section class="login-story"><p class="eyebrow">Cada mirada cuenta</p><h1>Pequeñas miradas.<br>Grandes futuros.</h1><img src="/assets/lupi.png" alt="Lupi saluda con sus anteojos"><p>Acompañamos la salud visual de la escuela a la consulta, y de la consulta a cada nuevo día.</p></section><main id="main" class="login-form"><div class="login-inner">${brand()}<h2>Bienvenido a tu espacio.</h2><p>Ingresá para acompañar cada mirada.</p><form data-form="login"><div class="error-text" role="alert"></div><div class="field"><label for="email">Correo electrónico</label><input id="email" name="email" type="email" autocomplete="username" required placeholder="tu.nombre@institucion.edu.ar"></div><div class="field"><label for="password">Contraseña</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="128"></div><button class="btn" type="submit">Ingresar ${icon('arrow')}</button></form>${state.config.demo?`<div class="mt"><p class="small muted">Explorá con datos ficticios</p><div class="demo-options">${Object.entries(ROLES).map(([key,value])=>btn(value,'demo',`data-role="${key}"`,'secondary')).join('')}</div></div>`:''}<p><a href="/ecosistema.html">Ver las aplicaciones VinTracker</a></p><p class="login-footer">Acceso reservado al equipo autorizado. Si necesitás una cuenta, contactá a la coordinación de tu institución.</p></div></main></div>`;}
function renderPage(){return ({inicio:dashboard,alumnos:studentsPage,tamizaje:screenPage,consultas:consultPage,anteojos:ordersPage,seguimiento:followPage,recursos:resources,admin:adminPage}[state.page]||dashboard)();}
function dashboard(){
  if(has('workshop'))return ordersPage();
  const a=state.students,screened=a.filter(p=>p.status!=='pending'),needs=a.filter(p=>['yellow','red','gray'].includes(p.status)),orders=a.filter(p=>p.orderStatus==='entregado');
  const metrics=[['Alumnos registrados',a.length,'En las escuelas de tu equipo','users'],['Tamizajes realizados',screened.length,'Alumnos con al menos un registro','eye'],['Para evaluar / repetir',needs.length,'Según el último tamizaje','clock'],['Anteojos entregados',orders.length,'Según la orden vigente','glasses']];
  const recent=[...a].sort((x,y)=>(y.screenDate||'').localeCompare(x.screenDate||'')).slice(0,5);
  return `${heading('Una mirada a tu comunidad','Todo lo necesario para acompañar la salud visual escolar.',btn(icon('plus')+' Nuevo alumno','new-student'))}<section class="hero"><div><div class="eyebrow">Haciendo la Vista Gorda</div><h2>Pequeñas miradas.<br>Grandes futuros.</h2><p>Detectar a tiempo es el primer paso.<br>Acompañar el recorrido hace la diferencia.</p><a class="btn" href="#tamizaje">Iniciar un tamizaje ${icon('arrow')}</a></div><div class="hero-art"><img src="/assets/lupi.png" alt="Lupi, nuestro compañero de salud visual"><span class="annotation">¡Cada mirada cuenta!</span></div></section><div class="metrics">${metrics.map(([label,num,note,ic])=>`<article class="metric"><span class="metric-icon">${icon(ic)}</span><p class="label">${label}</p><strong>${num}</strong><small>${note}</small></article>`).join('')}</div><div class="grid-main"><section class="panel"><div class="panel-head"><div><h2>Alumnos de tu comunidad</h2><p>Último resultado registrado</p></div><a class="text-btn" href="#alumnos">Ver todos</a></div>${studentTable(recent,true)}<div class="panel-foot">Cada resultado orienta el próximo paso. La evaluación profesional confirma la conducta.</div></section><div class="stats-side"><section class="panel"><div class="panel-head"><h2>Estado de los tamizajes</h2>${icon('eye')}</div><div class="panel-body"><div class="legend">${['green','yellow','red','gray'].map(s=>`<div class="legend-row"><span class="legend-label"><i class="swatch ${s}"></i>${STATUS[s].label}</span><strong>${screened.filter(p=>p.status===s).length}</strong></div>`).join('')}</div><div class="mt"><label for="coverage" class="small muted">Registrados con tamizaje: ${screened.length} de ${a.length}</label><progress id="coverage" class="meter" value="${screened.length}" max="${a.length||1}">${screened.length}</progress></div><p class="report-caption">Describe los registros del equipo; no es una estimación de prevalencia.</p></div></section><article class="tip-card">${icon('book')}<h3>Un buen comienzo, una prueba confiable.</h3><p>Revisá la distancia, la cartilla y la oclusión antes de cada tamizaje.</p><a class="text-btn" href="#recursos">Ver guía de preparación</a></article></div></div>`;
}
function studentTable(list,compact=false){if(!list.length)return empty('Todavía no hay alumnos para mostrar.','Registrá un alumno o ajustá los filtros.',!state.students.length?btn('Registrar alumno','new-student','', 'secondary'):'');return `<div class="table-wrap"><table><thead><tr><th>Alumno</th>${compact?'':'<th>Escuela</th>'}<th>Último tamizaje</th><th><span class="small">Ficha</span></th></tr></thead><tbody>${list.map(p=>`<tr><td><strong>${esc(p.name)}</strong><small>${esc(p.grade)} · ${age(p.dob)}</small></td>${compact?'':`<td>${esc(school(p.schoolId))}</td>`}<td>${status(p)}<small>${d(p.screenDate)}</small></td><td><button class="text-btn" data-action="student" data-id="${esc(p.id)}" aria-label="Abrir ficha de ${esc(p.name)}">Abrir ${icon('arrow')}</button></td></tr>`).join('')}</tbody></table></div>`;}
function studentsPage(){const q=state.query.toLocaleLowerCase('es');const filtered=state.students.filter(p=>(p.name.toLocaleLowerCase('es').includes(q)||(p.document||'').includes(q))&&(state.filter==='all'||p.status===state.filter));return `${heading('Cada alumno, una historia','Registro escolar y continuidad del cuidado.',btn(icon('plus')+' Nuevo alumno','new-student'))}<div class="toolbar"><div class="search">${icon('search')}<input type="search" id="student-search" aria-label="Buscar alumno por nombre o DNI" placeholder="Buscar por nombre o DNI…" value="${esc(state.query)}"></div><select id="status-filter" aria-label="Filtrar por estado"><option value="all">Todos los estados</option>${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${state.filter===k?'selected':''}>${v.label}</option>`).join('')}</select>${has('admin','clinician')?'<a class="btn secondary" href="/api/export" download>Indicadores CSV '+icon('download')+'</a>':''}</div><section class="panel" id="student-results">${studentTable(filtered)}</section><p class="report-caption">${filtered.length} de ${state.students.length} alumnos · La exportación contiene totales por escuela, sin nombres ni DNI.</p>`;}
function consultPage(){const list=[...state.students].sort((a,b)=>({red:0,yellow:1,gray:2,pending:3,green:4}[a.status]-{red:0,yellow:1,gray:2,pending:3,green:4}[b.status]));return `${heading('Consultas y derivaciones','El equipo profesional define el diagnóstico y el próximo paso.')}<div class="notice-box">${has('clinician')?'Ingresá a una ficha para registrar la consulta. Los asientos conservan autor, matrícula y fecha.':'Podés revisar el recorrido. La carga de diagnósticos y recetas está reservada al perfil profesional.'}</div><section class="panel"><div class="panel-head"><h2>Cola de atención</h2><span class="badge blue">${list.length} alumnos</span></div>${studentTable(list)}</section>`;}
function ordersPage(){const list=state.students.filter(p=>p.orderConsultId);return `${heading('Anteojos que llegan a destino','De la indicación profesional a la entrega registrada.')}<section class="panel"><div class="panel-head"><h2>Órdenes de anteojos</h2><span class="badge blue">${list.filter(x=>x.orderStatus!=='entregado').length} pendientes de entrega</span></div>${!list.length?empty('No hay órdenes de anteojos.','Las consultas con indicación de anteojos aparecerán aquí.'):`<div class="table-wrap"><table><thead><tr><th>Alumno</th><th>Escuela</th><th>Estado</th><th>Próximo paso</th></tr></thead><tbody>${list.map(p=>`<tr><td><strong>${esc(p.name)}</strong><small>${esc(p.grade)}</small></td><td>${esc(school(p.schoolId))}</td><td><span class="badge ${p.orderStatus==='entregado'?'green':'yellow'}">${esc(p.orderStatus)}</span></td><td>${p.orderStatus==='entregado'?btn('Ver entrega','student',`data-id="${p.id}"`,'secondary small'):btn(p.orderStatus==='preparado'?'Registrar entrega':'Preparar orden','order',`data-id="${p.id}"`,'secondary small')}</td></tr>`).join('')}</tbody></table></div>`}</section>`;}
function followPage(){const list=state.students.filter(p=>p.nextDate||p.status==='gray'||p.status==='red');return `${heading('Acompañar después del control','Uso de anteojos, derivaciones y nuevas evaluaciones.')}<section class="panel"><div class="panel-head"><h2>Alumnos con seguimiento</h2>${icon('clock')}</div>${!list.length?empty('No hay seguimientos registrados.','Las fechas definidas en consulta y las pruebas no evaluables aparecerán aquí.'):`<div class="table-wrap"><table><thead><tr><th>Alumno</th><th>Próximo control</th><th>Último seguimiento</th><th>Acción</th></tr></thead><tbody>${list.map(p=>`<tr><td><strong>${esc(p.name)}</strong><small>${esc(school(p.schoolId))}</small></td><td>${d(p.nextDate)}${p.nextDate&&p.nextDate<today()?'<small>Fecha alcanzada: revisar continuidad</small>':''}</td><td>${d(p.followupDate)}</td><td>${btn('Registrar seguimiento','followup',`data-id="${p.id}"`,'secondary small')}</td></tr>`).join('')}</tbody></table></div>`}</section>`;}
function field(label,name,value='',type='text',attrs=''){return `<div class="field"><label for="f-${name}">${label}</label><input id="f-${name}" name="${name}" type="${type}" value="${esc(value)}" ${attrs}></div>`;}
function select(label,name,options,value='',attrs=''){return `<div class="field"><label for="f-${name}">${label}</label><select id="f-${name}" name="${name}" ${attrs}>${options.map(([k,v])=>`<option value="${esc(k)}" ${String(value)===String(k)?'selected':''}>${esc(v)}</option>`).join('')}</select></div>`;}
function textarea(label,name,value='',attrs=''){return `<div class="field"><label for="f-${name}">${label}</label><textarea id="f-${name}" name="${name}" ${attrs}>${esc(value)}</textarea></div>`;}
function acuity(label,name,value=''){return select(label,name,[['','Seleccionar…'],...ACUITIES.map(n=>[n,`20/${n}`])],value);}
function modal(title,body,sub=''){const el=$('#modal');el.innerHTML=`<div class="modal-head"><div><h2 id="modal-title">${title}</h2>${sub?`<p>${sub}</p>`:''}</div><button class="icon-btn" data-action="close" aria-label="Cerrar ventana">${icon('close')}</button></div><div class="modal-body">${body}</div>`;if(!el.open)el.showModal();}
function formWrap(name,body,submit='Guardar',data=''){return `<form data-form="${name}" ${data}><div class="error-text" role="alert"></div>${body}<div class="form-actions"><button type="button" class="btn secondary" data-action="close">Cancelar</button><button type="submit" class="btn">${submit} ${icon('check')}</button></div></form>`;}
function studentForm(p={}){modal(p.id?'Editar datos escolares':'Un nuevo alumno',formWrap('student',`<div class="form-grid">${field('Nombre y apellido','name',p.name,'text','required minlength="3" maxlength="100" autocomplete="off"')}${field('Fecha de nacimiento','dob',p.dob,'date',`required max="${today()}"`)}${field('DNI (opcional)','document',p.document,'text','inputmode="numeric" pattern="[0-9]{7,9}" maxlength="9"')}${select('Escuela','schoolId',[['','Seleccionar…'],...state.schools.map(s=>[s.id,s.name])],p.schoolId,'required')}${field('Grado y sección','grade',p.grade,'text','required maxlength="40" placeholder="Ej. 3° A"')}${field('Adulto responsable','guardian',p.guardian,'text','required minlength="3" maxlength="100"')}${field('Contacto del adulto','contact',p.contact,'text','required minlength="6" maxlength="80"')}<div class="span-2"><label><input type="checkbox" name="consent" id="consent-check" ${p.consent?'checked':''}> La institución tiene autorización documentada para esta actividad y registro.</label></div><div class="consent-fields ${p.consent?'':'is-hidden'} span-2"><div class="form-grid">${field('Fecha de autorización','consentDate',p.consentDate||today(),'date',`max="${today()}"`)}${field('Referencia del documento resguardado','consentRef',p.consentRef,'text','maxlength="120" placeholder="Ej. AUT-2026-015"')}</div></div></div><div class="notice-box small">La autorización se resguarda en la institución. Esta casilla registra su existencia; no reemplaza el proceso de información y consentimiento.</div>`, 'Guardar alumno',p.id?`data-id="${p.id}" data-version="${p.version}"`:''));}
async function detail(id){const out=await api('/students/'+id);state.detail=out;const p=out.student;const canClinical=has('clinician');const buttons=[!has('workshop')?btn(icon('edit')+' Editar datos','edit-student','', 'secondary small'):'',!has('workshop')?btn('Nuevo tamizaje','screen-student',`data-id="${p.id}"`,'secondary small'):'',canClinical?btn('Registrar consulta','consult',`data-id="${p.id}"`,'small'):'',!has('workshop')?btn('Seguimiento','followup',`data-id="${p.id}"`,'secondary small'):'',btn(icon('print')+' Imprimir ficha','print','','secondary small')].join('');
  modal(esc(p.name),`<dl class="details-grid"><div><dt>Escuela</dt><dd>${esc(school(p.schoolId))}</dd></div><div><dt>Grado</dt><dd>${esc(p.grade)}</dd></div>${has('workshop')?`<div><dt>Orden vigente</dt><dd>${esc(p.orderStatus)}</dd></div>`:`<div><dt>Edad</dt><dd>${age(p.dob)} · ${d(p.dob)}</dd></div><div><dt>Adulto responsable</dt><dd>${esc(p.guardian)}</dd></div><div><dt>Contacto</dt><dd>${esc(p.contact)}</dd></div><div><dt>Autorización</dt><dd>${p.consent?'Documentada':'Pendiente'}</dd></div>`}</dl>${!has('workshop')?`<div class="notice-box">${status(p)}<p>${esc(p.screenReason||'Todavía no hay un tamizaje registrado.')}</p></div>`:rxTable(p.rx)}<div class="actions">${buttons}</div><section class="timeline"><h3 class="section-label">${has('teacher')?'Registro escolar':'Historial de registros'}</h3>${out.events.length?out.events.map(eventView).join(''):'<p class="muted small">Los registros aparecerán en orden cronológico, con los más recientes primero.</p>'}</section>`,has('teacher')?'Los diagnósticos y recetas están reservados al equipo sanitario.':'Registro del equipo · acceso según función');
}
function rxTable(rx){if(!rx)return '';return `<div class="rx"><table><thead><tr><th>Ojo</th><th>Esfera</th><th>Cilindro</th><th>Eje</th></tr></thead><tbody>${['od','oi'].map(e=>`<tr><td>${e.toUpperCase()}</td><td>${esc(rx[e]?.sphere)}</td><td>${esc(rx[e]?.cylinder)}</td><td>${esc(rx[e]?.axis)}°</td></tr>`).join('')}</tbody></table></div>`;}
function eventView(ev){const titles={screen:'Tamizaje escolar',consult:'Consulta profesional',order:'Orden de anteojos',followup:'Seguimiento'};let body='';if(ev.type==='screen')body=`${status(ev)}<p>OD: ${ev.od?'20/'+ev.od:'No evaluable'} · OI: ${ev.oi?'20/'+ev.oi:'No evaluable'}${ev.binocular?' · Binocular: 20/'+ev.binocular:''}</p><p>${esc(ev.reason)}</p><p class="muted">${esc(ev.chart)} · ${esc(ev.distance)} m · ${esc(ev.correction)} · ${esc(ev.protocol)}</p>${ev.alertContact?`<p><strong>Comunicación:</strong> ${esc(ev.alertContact)}</p>`:''}`;
if(ev.type==='consult')body=`<p><strong>${esc(ev.diagnosis)}</strong></p><p>Conducta: ${esc({control:'Control',anteojos:'Indicación de anteojos',derivacion:'Derivación'}[ev.plan])} · Seguimiento: ${d(ev.nextDate)}</p>${rxTable(ev.rx)}${ev.referral?`<p>${esc(ev.referral)}</p>`:''}`;
if(ev.type==='order')body=`<span class="badge ${ev.state==='entregado'?'green':'yellow'}">${esc(ev.state)}</span><p>Armazón: ${esc(ev.frame)} · ${esc(ev.material)}${ev.recipient?' · Recibió: '+esc(ev.recipient):''}</p>`;
if(ev.type==='followup')body=`<p><strong>${esc(outcomeLabel(ev.outcome))}</strong></p>`;
return `<article class="event"><h3>${titles[ev.type]}</h3><p class="meta">${d(ev.date)} · ${esc(ev.author)}${ev.type==='consult'?' · '+esc(ev.license):''}</p>${body}${ev.notes?`<p>${esc(ev.notes)}</p>`:''}</article>`;}
function outcomeLabel(x){return {usa:'Usa anteojos habitualmente',irregular:'Uso irregular',no_usa:'No usa los anteojos',pendiente:'Pendiente de evaluación / entrega',derivacion_atendida:'Derivación con atención confirmada',derivacion_pendiente:'Derivación pendiente'}[x]||x;}
function startScreen(id=''){state.step=0;state.wizard={studentId:id,date:today(),od:'',oi:'',binocular:'',unable:false,conditions:false,chart:'Sloan',distance:3,correction:'no usa anteojos',symptoms:[],alerts:[],alertContact:'',notes:''};$('#modal').close();navigate('tamizaje');}
function screenPage(){if(!state.wizard)state.wizard={studentId:'',date:today(),od:'',oi:'',binocular:'',unable:false,conditions:false,chart:'Sloan',distance:3,correction:'no usa anteojos',symptoms:[],alerts:[],alertContact:'',notes:''};const w=state.wizard,p=state.students.find(x=>x.id===w.studentId);let body='';
  if(!state.students.length)return heading('Tamizaje guiado','Un recorrido claro, ojo por ojo.')+empty('Primero registrá un alumno.','Necesitamos una ficha y la referencia de autorización para comenzar.',btn('Nuevo alumno','new-student'));
  if(state.step===0)body=`<h2>¿A quién vamos a acompañar?</h2><p class="description">Elegí la ficha del alumno y la fecha de la actividad.</p><div class="form-grid">${select('Alumno','studentId',[['','Seleccionar alumno…'],...state.students.map(p=>[p.id,p.name+' · '+p.grade])],w.studentId,'required')}${field('Fecha de tamizaje','date',w.date,'date',`required max="${today()}"`)}</div><div class="notice-box">Se registra una prueba realizada con cartilla estandarizada. La app no mide visión mediante la cámara o esta pantalla.</div>`;
  if(state.step===1)body=`<h2>Preparar bien es cuidar el resultado.</h2><p class="description">${esc(p?.name)} · ${age(p?.dob)}. Verificá las instrucciones de la cartilla y la comprensión de la consigna.</p><div class="form-grid">${select('Cartilla estandarizada','chart',['Sloan','HOTV','LEA','E direccional','C de Landolt'].map(x=>[x,x]),w.chart)}${field('Distancia indicada por la cartilla (m)','distance',w.distance,'number','required min="1" max="6" step="0.1"')}${select('Corrección durante la prueba','correction',['no usa anteojos','con corrección habitual','sin corrección'].map(x=>[x,x]),w.correction)}</div><label><input type="checkbox" name="conditions" ${w.conditions?'checked':''}> Verifiqué distancia física, iluminación, cartilla, comprensión y oclusión sin presión. Los ojos se evalúan por separado.</label><p class="small muted">Si no se cumplen estas condiciones, podés continuar para dejar constancia de una prueba no evaluable.</p><h3 class="section-label">Observaciones previas</h3>${Object.entries(SYMPTOMS).map(([k,v])=>`<label><input type="checkbox" name="symptoms" value="${k}" ${w.symptoms.includes(k)?'checked':''}>${v}</label>`).join('')}<h3 class="section-label">¿Se observó un signo de alarma?</h3><div class="notice-box warning">Ante una alarma, contactá al equipo sanitario sin esperar al operativo. Registrá abajo la comunicación; no demores la atención para terminar esta prueba.</div>${Object.entries(ALERTS).map(([k,v])=>`<label><input type="checkbox" name="alerts" value="${k}" ${w.alerts.includes(k)?'checked':''}>${v}</label>`).join('')}${field('Contacto sanitario e indicación recibida (si hubo alerta)','alertContact',w.alertContact,'text','maxlength="200"')}`;
  if(state.step===2)body=`<h2>Registrar el resultado de cada ojo.</h2><p class="description">Ingresá la última línea superada siguiendo el procedimiento de la cartilla. No calcules ni deduzcas el resultado binocular.</p><label><input type="checkbox" name="unable" id="unable-check" ${w.unable?'checked':''}> No fue posible completar la prueba</label><div class="form-grid acuity-fields ${w.unable?'is-hidden':''}">${acuity('Ojo derecho (OD)','od',w.od)}${acuity('Ojo izquierdo (OI)','oi',w.oi)}${acuity('Binocular (opcional, sólo si se midió)','binocular',w.binocular)}</div>${textarea('Observaciones / motivo de prueba no evaluable','notes',w.notes,'maxlength="1500"')}<div class="notice-box small">Un resultado incompleto se registra como tal. No se reemplaza por el resultado del otro ojo ni se interpreta como visión conservada.</div>`;
  if(state.step===3){const c=classify(screenData(w),p.dob);body=`<h2>Revisá antes de guardar.</h2><p class="description">${esc(p.name)} · ${d(w.date)} · Protocolo ${PROTOCOL}</p><div class="result-card ${c.status}">${status(c)}<h3>${STATUS[c.status].label}</h3><p>${esc(c.reason)}</p></div><dl class="details-grid"><div><dt>Ojo derecho</dt><dd>${w.unable?'No evaluable':'20/'+esc(w.od)}</dd></div><div><dt>Ojo izquierdo</dt><dd>${w.unable?'No evaluable':'20/'+esc(w.oi)}</dd></div><div><dt>Cartilla / distancia</dt><dd>${esc(w.chart)} · ${esc(w.distance)} m</dd></div></dl><p class="small muted">Este resultado orienta el seguimiento y no constituye un diagnóstico. El servidor vuelve a verificar los datos y calcula la clasificación al guardar.</p>`;}
  return `<div class="wizard">${heading('Un tamizaje, paso a paso','Una prueba estandarizada. Un registro claro.')}<div class="steps" aria-label="Pasos del tamizaje">${['Alumno','Preparación','Resultados','Revisión'].map((v,i)=>`<div class="step ${state.step===i?'active':''}" ${state.step===i?'aria-current="step"':''}><span>${i+1}</span>${v}</div>`).join('')}</div><section class="panel"><div class="panel-body"><form data-form="wizard"><div class="error-text" role="alert"></div>${body}<div class="form-actions">${state.step?btn('Volver','wizard-back','type="button"','secondary'):''}<button type="submit" class="btn">${state.step===3?'Guardar tamizaje':'Continuar'} ${icon(state.step===3?'check':'arrow')}</button></div></form></div></section></div>`;
}
function screenData(w){return {...w,od:w.unable?null:Number(w.od),oi:w.unable?null:Number(w.oi),binocular:w.binocular?Number(w.binocular):null,distance:Number(w.distance)};}
function saveWizard(form){const f=new FormData(form),w=state.wizard;if(state.step===0){w.studentId=f.get('studentId');w.date=f.get('date');}if(state.step===1){w.chart=f.get('chart');w.distance=Number(f.get('distance'));w.correction=f.get('correction');w.conditions=f.has('conditions');w.symptoms=f.getAll('symptoms');w.alerts=f.getAll('alerts');w.alertContact=f.get('alertContact');}if(state.step===2){w.unable=f.has('unable');w.od=f.get('od');w.oi=f.get('oi');w.binocular=f.get('binocular');w.notes=f.get('notes');}}
async function consultForm(id){const out=await api('/students/'+id);state.detail=out;modal('Registrar consulta',formWrap('consult',`<div class="notice-box">${esc(out.student.name)} · ${age(out.student.dob)}. Autor: ${esc(state.user.name)} · ${esc(state.user.license)}. Para rectificar un asiento, dejá la aclaración en una nueva consulta.</div><div class="form-grid">${field('Fecha de consulta','date',today(),'date',`required max="${today()}"`)}${select('Conducta','plan',[['control','Control'],['anteojos','Indicación de anteojos'],['derivacion','Derivación']], 'control')}${field('Diagnóstico / impresión profesional','diagnosis','','text','required minlength="3" maxlength="800"')}${field('Fecha prevista de seguimiento','nextDate',today(),'date','required')}</div><div class="rx-fields is-hidden"><h3 class="section-label">Receta registrada por el profesional</h3><div class="form-grid">${['od','oi'].map(eye=>`<div><h3 class="section-label">${eye==='od'?'Ojo derecho':'Ojo izquierdo'}</h3>${field('Esfera','sphere_'+eye,'','number','min="-30" max="30" step="0.25"')}${field('Cilindro','cylinder_'+eye,'','number','min="-15" max="15" step="0.25"')}${field('Eje (°)','axis_'+eye,'','number','min="0" max="180" step="1"')}</div>`).join('')}</div></div><div class="referral-fields is-hidden">${textarea('Destino y motivo de derivación','referral','','maxlength="500"')}</div>${textarea('Examen, indicaciones y aclaraciones','notes','','maxlength="2500"')}`,'Guardar consulta',`data-id="${id}" data-version="${out.student.version}"`));}
async function orderForm(id){const out=await api('/students/'+id);state.detail=out;const p=out.student,last=out.events.find(e=>e.type==='order'&&e.consultId===p.orderConsultId),consult=out.events.find(e=>e.type==='consult');const deliver=p.orderStatus==='preparado';modal(deliver?'Registrar entrega':'Preparar anteojos',formWrap('order',`<p><strong>${esc(p.name)}</strong> · ${esc(school(p.schoolId))}</p>${rxTable(p.rx||consult?.rx)}<div class="form-grid mt">${field('Fecha','date',today(),'date',`required max="${today()}"`)}${field('Código / modelo del armazón','frame',last?.frame||'','text','required minlength="2" maxlength="100"')}${select('Material indicado','material',['Policarbonato','Orgánico','Otro indicado por profesional'].map(x=>[x,x]),last?.material||'Policarbonato')}${deliver?field('Nombre del adulto receptor','recipient','','text','required minlength="3" maxlength="100"'):''}</div><div class="notice-box small">La preparación utiliza la receta profesional vigente. La entrega queda asociada a esa orden y a quien la recibió.</div>`,deliver?'Confirmar entrega':'Guardar preparación',`data-id="${id}" data-version="${p.version}" data-consult="${p.orderConsultId}" data-state="${deliver?'entregado':'preparado'}"`));}
async function followForm(id){const out=await api('/students/'+id);state.detail=out;modal('Registrar seguimiento',formWrap('followup',`<p class="muted">${esc(out.student.name)}</p><div class="form-grid mt">${field('Fecha','date',today(),'date',`required max="${today()}"`)}${select('Resultado observado','outcome',['usa','irregular','no_usa','pendiente','derivacion_atendida','derivacion_pendiente'].map(x=>[x,outcomeLabel(x)]))}</div>${textarea('Observaciones y próximo paso acordado','notes','','required minlength="5" maxlength="1500"')}`,'Guardar seguimiento',`data-id="${id}" data-version="${out.student.version}"`));}
function resources(){return `${heading('Herramientas para acompañar','Indicaciones claras para el aula, la consulta y las familias.')}<div class="resource-grid"><article class="resource-card"><span class="resource-number">01</span><h3>Antes de empezar</h3><p>Prepará el espacio y ayudá al niño a comprender la actividad.</p>${btn('Leer la guía','guide','','secondary')}</article><article class="resource-card"><span class="resource-number">02</span><h3>Entender los resultados</h3><p>Qué significa cada estado y cómo organizar el próximo paso.</p>${btn('Ver el protocolo','protocol','','secondary')}</article><article class="resource-card"><span class="resource-number">03</span><h3>Practicamos con Lupi</h3><p>Una actividad para familiarizarse con direcciones. Sin puntajes clínicos.</p>${btn('Abrir actividad','practice','','secondary')}</article></div><section class="panel mt"><div class="panel-head"><h2>Para conversar con las familias</h2>${icon('heart')}</div><div class="panel-body"><ul class="bullets"><li>Explicar que el tamizaje puede indicar la necesidad de una consulta; no confirma por sí solo una enfermedad.</li><li>Ante molestias, dificultades visuales o dudas, consultar al equipo de salud aunque el tamizaje haya cumplido el criterio.</li><li>Acompañar el uso de los anteojos según indicación profesional, su cuidado y los controles acordados.</li><li>Evitar que el resultado se comunique públicamente frente al curso. Cada ficha es confidencial.</li></ul></div></section><p class="report-caption">Referencia del criterio etario: <a href="https://aapos.org/members/vision-screening-guidelines" target="_blank" rel="noopener noreferrer">AAPOS · Vision Screening Recommendations</a>. La adaptación local está a cargo de la dirección sanitaria.</p>`;}
function guide(){modal('Antes de empezar',`<ol class="bullets"><li>Confirmar ficha, autorización y comprensión. Adaptar la consigna a la edad.</li><li>Usar una cartilla estandarizada aprobada por el equipo y la distancia indicada por el fabricante.</li><li>Medir la distancia físicamente y mantener iluminación y contraste adecuados.</li><li>Ocluir un ojo sin presión y sin permitir que el niño mire por los costados. Repetir con el otro ojo.</li><li>Registrar si usa corrección habitual y la última línea superada según el procedimiento de la cartilla.</li><li>Si no puede completar, consignar “No evaluable” y el motivo.</li><li>Comunicar los signos de alarma al equipo sanitario sin esperar al operativo.</li></ol><div class="notice-box">La pantalla de esta app no es una cartilla clínica. La actividad de Lupi sólo ayuda a comprender direcciones.</div>`);}
function protocol(){modal('Protocolo de registro '+PROTOCOL,`<p>Referencia etaria AAPOS: identificar la mayoría de los optotipos de la línea correspondiente, con evaluación de cada ojo.</p><div class="rx"><table><thead><tr><th>Edad</th><th>Umbral de referencia</th></tr></thead><tbody><tr><td>36 a 47 meses</td><td>20/50</td></tr><tr><td>48 a 59 meses</td><td>20/40</td></tr><tr><td>5 a 17 años</td><td>20/32</td></tr></tbody></table></div><ul class="bullets"><li><strong>Cumple criterio:</strong> ambos ojos alcanzan el umbral, condiciones válidas y sin observaciones.</li><li><strong>Requiere evaluación:</strong> falla de umbral, observaciones o asimetría cercana a dos líneas logMAR. La regla de asimetría y la conducta por observaciones requieren aprobación local.</li><li><strong>Alerta comunicada:</strong> signo de alarma registrado. Solicitar atención sanitaria sin esperar al operativo.</li><li><strong>No evaluable:</strong> prueba incompleta, condiciones insuficientes o edad fuera del alcance.</li></ul><div class="notice-box">Los colores no diagnostican enfermedades ni determinan por sí solos la gravedad. El profesional define atención y seguimiento.</div><p class="small"><a href="https://aapos.org/members/vision-screening-guidelines" target="_blank" rel="noopener noreferrer">Consultar fuente AAPOS</a></p>`);}
function practice(){state.practice=crypto.getRandomValues(new Uint32Array(1))[0]%4;modal('Practicamos con Lupi',`<div class="practice"><div class="notice-box">Actividad de comprensión. No mide agudeza visual ni guarda respuestas en la ficha.</div><p>¿Hacia dónde apuntan los brazos de la letra E?</p><div class="letter rot-${state.practice}" aria-label="Letra E para la actividad visual">E</div><div class="directions">${[['Derecha',0],['Abajo',1],['Izquierda',2],['Arriba',3]].map(([t,n])=>btn(t,'direction',`data-direction="${n}"`,'secondary')).join('')}</div><p id="practice-feedback" role="status" class="mt small muted">Podés probar todas las veces que quieras.</p></div>`);}
function help(){return `<aside class="help" aria-label="Ayuda de Lupi"><h3>¡Hola! Soy Lupi.</h3><p>${({tamizaje:'Vamos paso a paso. Si el niño no comprende o no completa la prueba, registrá el motivo: también es información útil.',anteojos:'Cada anteojo tiene un recorrido: indicación, preparación y entrega. No olvides registrar quién lo recibió.',alumnos:'Cada alumno tiene su propia ficha. Antes de crear una, buscá si ya está registrado.',seguimiento:'El cuidado continúa después de la consulta. Registrá cómo sigue el alumno y el próximo paso.'}[state.page]||'Te acompaño a cuidar cada mirada. ¿Revisamos cómo preparar la actividad?')}</p><div class="actions">${btn('Ver guía','guide','','secondary small')}${btn('Practicar','practice','','small')}<button class="text-btn" data-action="help">Cerrar</button></div></aside>`;}
function adminPage(){return `${heading('Organizar el equipo','Escuelas, perfiles y trazabilidad de los registros.',btn(icon('plus')+' Nueva cuenta','new-user'))}${!state.config.clinical?'<div class="notice-box warning">Registro real pendiente de habilitación. Revisá la guía de instalación con la coordinación institucional.</div>':''}<div id="admin-content"><p class="muted">Cargando cuentas y escuelas…</p></div>`;}
async function loadAdmin(){try{const out=await api('/admin');state.admin=out;if(state.page!=='admin')return;$('#admin-content').innerHTML=`<div class="admin-grid"><section class="panel"><div class="panel-head"><h2>Cuentas del equipo</h2>${icon('shield')}</div><div class="table-wrap"><table><thead><tr><th>Persona</th><th>Perfil</th><th>Acceso</th></tr></thead><tbody>${out.users.map(u=>`<tr><td><strong>${esc(u.name)}</strong><small>${esc(u.email)}</small></td><td>${esc(ROLES[u.role])}<small>${u.active?'Activa':'Desactivada'}</small></td><td>${u.id!==state.user.id?btn('Gestionar','manage-user',`data-id="${u.id}"`,'secondary small'):'<span class="muted small">Tu cuenta</span>'}</td></tr>`).join('')}</tbody></table></div></section><section><div class="page-heading"><h2>Escuelas</h2>${btn('Agregar','new-school','','secondary small')}</div>${out.schools.map(s=>`<article class="school-card"><h3>${esc(s.name)}</h3><p class="small muted">CUE ${esc(s.cue)} · ${esc(s.location)}</p></article>`).join('')||'<p class="muted">Agregá la primera escuela.</p>'}</section></div><section class="panel mt"><div class="panel-head"><h2>Actividad reciente</h2><span class="small muted">Últimos 100 eventos</span></div><div class="panel-body audit">${out.audit.map(a=>`<div class="audit-item"><strong>${esc(auditLabel(a.action))}</strong> · ${esc(a.author||'Acceso no identificado')}<small>${new Date(a.createdAt).toLocaleString('es-AR',{timeZone:APP_TIME_ZONE})} · Ref. ${esc(a.subject.slice(0,8))}</small></div>`).join('')||'<p class="muted">Sin actividad todavía.</p>'}</div></section>`;}catch(e){if($('#admin-content'))$('#admin-content').innerHTML=`<div class="error-text">${esc(e.message)}</div>`;}}
function auditLabel(s){return {login:'Ingreso',login_failed:'Intento de ingreso fallido',list_view:'Consulta del listado',student_view:'Consulta de ficha',student_created:'Alta de alumno',student_updated:'Cambio de datos escolares',screen_created:'Tamizaje registrado',consult_created:'Consulta registrada',order_created:'Orden actualizada',followup_created:'Seguimiento registrado',school_created:'Alta de escuela',user_created:'Alta de cuenta',user_updated:'Cambio de cuenta',password_changed:'Cambio de contraseña',aggregate_export:'Exportación de indicadores'}[s]||s;}
function userForm(){modal('Nueva cuenta',formWrap('user',`<div class="form-grid">${field('Nombre y apellido','name','','text','required minlength="3" maxlength="100"')}${field('Correo electrónico','email','','email','required maxlength="150" autocomplete="off"')}${select('Perfil de acceso','role',Object.entries(ROLES),'teacher')}${field('Contraseña inicial','password','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}${field('Matrícula (sólo profesionales)','license','','text','maxlength="80"')}</div><h3 class="section-label">Escuelas asignadas al docente</h3>${state.schools.map(s=>`<label><input type="checkbox" name="schools" value="${s.id}">${esc(s.name)}</label>`).join('')}<p class="small muted">Compartí las credenciales por un canal institucional. El usuario puede cambiar su contraseña al ingresar.</p>`,'Crear cuenta'));}
async function eventSave(form,type,data){await api('/students/'+form.dataset.id+'/events',{method:'POST',body:{type,expectedVersion:Number(form.dataset.version),data}});await refresh();$('#modal').close();render();notify('Registro guardado correctamente.');}
document.addEventListener('submit',async event=>{
  const form=event.target.closest('[data-form]');if(!form)return;event.preventDefault();const error=form.querySelector('.error-text');error.textContent='';const submit=form.querySelector('[type=submit]');submit.disabled=true;const f=new FormData(form),b=Object.fromEntries(f);try{
    const name=form.dataset.form;
    if(name==='login'){Object.assign(state,await api('/login',{method:'POST',body:b}));await refresh();render();}
    if(name==='student'){b.consent=f.has('consent');b.version=Number(form.dataset.version);await api('/students'+(form.dataset.id?'/'+form.dataset.id:''),{method:form.dataset.id?'PUT':'POST',body:b});await refresh();$('#modal').close();render();notify('Ficha escolar guardada.');}
    if(name==='wizard'){
      saveWizard(form);const w=state.wizard,p=state.students.find(x=>x.id===w.studentId);
      if(state.step===0){if(!p)throw Error('Seleccioná un alumno.');if(!p.consent)throw Error('La ficha necesita una autorización documentada antes de realizar el tamizaje.');state.screenVersion=p.version;}
      if(state.step===1&&w.alerts.length&&w.alertContact.trim().length<5)throw Error('Registrá a quién se comunicó la alerta y la indicación recibida.');
      if(state.step===2){if(!w.unable&&(!w.od||!w.oi))throw Error('Registrá el resultado de ambos ojos o marcá “No fue posible completar”.');if(w.unable&&w.notes.trim().length<5)throw Error('Explicá el motivo de la prueba no evaluable.');}
      if(state.step<3){state.step++;render();$('#main').focus();}else{const result=await api('/students/'+w.studentId+'/events',{method:'POST',body:{type:'screen',expectedVersion:state.screenVersion,data:screenData(w)}});state.wizard=null;state.step=0;await refresh();navigate('alumnos');modal('Tamizaje guardado',`<div class="result-card ${result.status}">${status(result)}<h3>${esc(p.name)}</h3><p>${esc(result.reason)}</p></div><div class="actions">${btn('Abrir ficha','student',`data-id="${p.id}"`)}${btn('Otro tamizaje','new-screen','','secondary')}</div>`);}
    }
    if(name==='consult'){const rx={};for(const eye of ['od','oi']){rx[eye]={};for(const [field,key] of [['sphere','sphere'],['cylinder','cylinder'],['axis','axis']]){const value=f.get(field+'_'+eye);if(b.plan==='anteojos'&&value==='')throw Error('Completá esfera, cilindro y eje de ambos ojos, incluido cero si corresponde.');rx[eye][key]=Number(value);}}await eventSave(form,'consult',{...b,rx});}
    if(name==='order')await eventSave(form,'order',{...b,state:form.dataset.state,consultId:form.dataset.consult});
    if(name==='followup')await eventSave(form,'followup',b);
    if(name==='school'){await api('/schools',{method:'POST',body:b});await refresh();$('#modal').close();render();notify('Escuela agregada.');}
    if(name==='user'){b.schools=f.getAll('schools');await api('/users',{method:'POST',body:b});$('#modal').close();render();notify('Cuenta creada.');}
    if(name==='manage-user'){const body={active:b.active==='true'};if(b.password)body.password=b.password;await api('/users/'+form.dataset.id,{method:'PATCH',body});$('#modal').close();render();notify('Acceso actualizado. Las sesiones anteriores se cerraron.');}
    if(name==='password'){if(b.password!==b.repeat)throw Error('Las contraseñas nuevas no coinciden.');Object.assign(state,await api('/password',{method:'POST',body:b}));$('#modal').close();notify('Contraseña actualizada.');}
  }catch(e){error.textContent=e.message;error.scrollIntoView({block:'nearest'});}finally{submit.disabled=false;}
});
document.addEventListener('click',async event=>{
  if(event.target.closest('a.skip')){event.preventDefault();$('#main').focus();return;}
  const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;try{
    if(action==='close')$('#modal').close();
    if(action==='menu')$('.sidebar').classList.toggle('open');
    if(action==='logout'){await api('/logout',{method:'POST',body:{}});state.user=null;state.students=[];state.schools=[];state.detail=null;state.wizard=null;state.help=false;render();}
    if(action==='demo'){Object.assign(state,await api('/demo',{method:'POST',body:{role:target.dataset.role}}));state.page='inicio';state.wizard=null;state.detail=null;state.query='';state.filter='all';$('#modal').close();await refresh();location.hash='inicio';render();}
    if(action==='roles')modal('Explorar otro perfil',`<div class="notice-box">Todas las cuentas y fichas de este entorno son ficticias.</div><div class="demo-options">${Object.entries(ROLES).map(([key,value])=>btn(value,'demo',`data-role="${key}"`,'secondary')).join('')}</div>`);
    if(action==='new-student'){if(!state.schools.length)throw Error('Primero agregá una escuela desde Administración.');studentForm();}
    if(action==='edit-student')studentForm(state.detail.student);
    if(action==='student')await detail(target.dataset.id);
    if(action==='screen-student'||action==='new-screen')startScreen(target.dataset.id||'');
    if(action==='wizard-back'){saveWizard(target.closest('form'));state.step--;render();}
    if(action==='consult')await consultForm(target.dataset.id);
    if(action==='order')await orderForm(target.dataset.id);
    if(action==='followup')await followForm(target.dataset.id);
    if(action==='print')window.print();
    if(action==='guide')guide();
    if(action==='protocol')protocol();
    if(action==='help'){state.help=!state.help;const old=$('.help');if(old)old.remove();if(state.help)$('#app').insertAdjacentHTML('beforeend',help());$('.mascot-launch').setAttribute('aria-expanded',String(state.help));$('.mascot-launch').setAttribute('aria-label',state.help?'Cerrar ayuda de Lupi':'Abrir ayuda de Lupi');}
    if(action==='practice')practice();
    if(action==='direction'){const correct=Number(target.dataset.direction)===state.practice;$('#practice-feedback').textContent=correct?'¡Esa es la dirección! Podés practicar otra vez.':'Mirá hacia qué lado se abren los tres brazos. Probá de nuevo.';if(correct){const next=document.createElement('button');next.className='btn secondary small';next.dataset.action='practice';next.textContent='Otra dirección';$('#practice-feedback').append(document.createElement('br'),next);}}
    if(action==='new-school')modal('Agregar escuela',formWrap('school',`${field('Nombre de la escuela','name','','text','required minlength="3" maxlength="100"')}${field('CUE','cue','','text','required minlength="3" maxlength="30"')}${field('Localidad / paraje','location','','text','required minlength="3" maxlength="100"')}`,'Agregar escuela'));
    if(action==='new-user')userForm();
    if(action==='manage-user'){const u=state.admin.users.find(x=>x.id===target.dataset.id);modal('Gestionar acceso',formWrap('manage-user',`<p><strong>${esc(u.name)}</strong> · ${esc(ROLES[u.role])}</p><div class="mt">${select('Estado de cuenta','active',[['true','Activa'],['false','Desactivada']],String(u.active))}${field('Nueva contraseña (dejar vacía para conservar)','password','','password','minlength="12" maxlength="128" autocomplete="new-password"')}</div><p class="small muted">Guardar cerrará todas las sesiones de esta cuenta.</p>`,'Guardar acceso',`data-id="${u.id}"`));}
    if(action==='password')modal('Cambiar mi contraseña',formWrap('password',`${field('Contraseña actual','current','','password','required autocomplete="current-password"')}${field('Nueva contraseña','password','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}${field('Repetir nueva contraseña','repeat','','password','required minlength="12" maxlength="128" autocomplete="new-password"')}`,'Actualizar contraseña'));
  }catch(e){notify(e.message);}
});
document.addEventListener('change',event=>{const el=event.target;if(el.id==='consent-check')$('.consent-fields').classList.toggle('is-hidden',!el.checked);if(el.id==='unable-check')$('.acuity-fields').classList.toggle('is-hidden',el.checked);if(el.name==='plan'){const v=el.value;$('.rx-fields').classList.toggle('is-hidden',v!=='anteojos');$('.referral-fields').classList.toggle('is-hidden',v!=='derivacion');}if(el.id==='status-filter'){state.filter=el.value;render();}});
document.addEventListener('input',event=>{if(event.target.id==='student-search'){const start=event.target.selectionStart;state.query=event.target.value;const q=state.query.toLocaleLowerCase('es');const filtered=state.students.filter(p=>(p.name.toLocaleLowerCase('es').includes(q)||(p.document||'').includes(q))&&(state.filter==='all'||p.status===state.filter));$('#student-results').innerHTML=studentTable(filtered);const caption=$('.report-caption');if(caption)caption.textContent=`${filtered.length} de ${state.students.length} alumnos · La exportación contiene totales por escuela, sin nombres ni DNI.`;if(start!==null)try{event.target.setSelectionRange(start,start);}catch{}}});
window.addEventListener('hashchange',()=>{state.page=location.hash.slice(1).split('?')[0]||'inicio';render();window.scrollTo(0,0);});
window.addEventListener('online',()=>notify('Conexión disponible. Podés volver a guardar.'));
window.addEventListener('offline',()=>notify('Se perdió la conexión. Conservá el formulario para reintentar.'));
async function init(){try{state.config=await api('/config');try{Object.assign(state,await api('/me'));await refresh();}catch(e){if(state.user)throw e;}state.page=location.hash.slice(1)||'inicio';render();}catch(e){$('#app').innerHTML=`<main id="main" class="loading"><h1>No pudimos conectar.</h1><p>${esc(e.message)}</p><a class="btn" href="/">Volver a intentar</a></main>`;}}
export const ready=init();
