import ExcelJS from 'exceljs';
const ink='472E25',peach='FFD2A2',blue='E4F0F3',cream='FFF8EB',muted='756254';
export const INDICATORS=[['Registrados','Alumnos con ficha en la escuela.'],['Evaluados','Alumnos con al menos un tamizaje, incluida una prueba no evaluable.'],['Cumple criterio','Último tamizaje con criterio cumplido. No descarta todos los problemas visuales.'],['Requiere evaluación','Último tamizaje que indica una evaluación profesional.'],['Alerta comunicada','Último tamizaje con una alerta comunicada al equipo sanitario.'],['No evaluable','Último tamizaje incompleto, con condiciones insuficientes o fuera del rango de edad.'],['Anteojos pendientes','Órdenes de la receta vigente que todavía no figuran entregadas.'],['Anteojos entregados','Alumnos con entrega registrada para su receta vigente.'],['Cobertura de registro','Evaluados / registrados. No representa cobertura sobre la matrícula escolar.']];
export function schoolIndicators(schools,students){return schools.map(s=>{const a=students.filter(p=>p.schoolId===s.id);return [s.name,a.length,a.filter(p=>p.status!=='pending').length,...['green','yellow','red','gray'].map(v=>a.filter(p=>p.status===v).length),a.filter(p=>p.orderStatus&&p.orderStatus!=='entregado').length,a.filter(p=>p.orderStatus==='entregado').length];});}
export async function excelReport(rows,{name='Salud visual escolar',date=new Date()}={}){
 const wb=new ExcelJS.Workbook();wb.creator='Salud Visión';wb.created=date;wb.calcProperties.fullCalcOnLoad=true;
 const summary=wb.addWorksheet('Resumen'),schools=wb.addWorksheet('Escuelas'),guide=wb.addWorksheet('Guía');summary.properties.tabColor={argb:ink};guide.properties.tabColor={argb:muted};
 for(const sheet of wb.worksheets){sheet.views=[{showGridLines:false}];sheet.properties.defaultRowHeight=23;sheet.pageSetup={paperSize:9,orientation:sheet===schools?'landscape':'portrait',fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.3,right:.3,top:.4,bottom:.4,header:.2,footer:.2}};sheet.headerFooter.oddFooter='Salud Visión — &P / &N';}
 function band(sheet,range,text,color=ink){sheet.mergeCells(range);const c=sheet.getCell(range.split(':')[0]);c.value=text;c.font={name:'Arial',size:16,bold:true,color:{argb:ink}};if(color!==ink)c.fill={type:'pattern',pattern:'solid',fgColor:{argb:color}};else c.border={bottom:{style:'thin',color:{argb:peach}}};c.alignment={vertical:'middle',wrapText:true};}
 band(schools,'A1:J2',name+' · Detalle por escuela');schools.mergeCells('A3:J3');schools.getCell('A3').value='Estado al momento de exportar. Cada alumno se cuenta una vez por indicador.';
 schools.getRow(4).values=['Exportado (UTC)',date];schools.getCell('B4').numFmt='dd/mm/yyyy hh:mm';schools.getRow(6).values=['Escuela',...INDICATORS.map(x=>x[0])];schools.getRow(6).height=46;
 schools.columns.forEach((c,i)=>c.width=i===0?34:i===9?19:18);
 const dataEnd=6+Math.max(rows.length,1);
 rows.forEach((row,i)=>{const n=i+7;schools.getRow(n).values=[...row,{formula:`IF(B${n}=0,"",C${n}/B${n})`,result:row[1]?row[2]/row[1]:''}];});
 if(!rows.length){schools.getCell('A7').value='Sin escuelas registradas';for(let c=2;c<=9;c++)schools.getRow(7).getCell(c).value=0;}
 const totals=Array.from({length:8},(_,i)=>rows.reduce((sum,r)=>sum+r[i+1],0));
 const totalRow=dataEnd+2;schools.getCell('A'+totalRow).value='TOTAL';for(let i=0;i<8;i++){const col=String.fromCharCode(66+i);schools.getCell(col+totalRow).value={formula:`SUM(${col}7:${col}${dataEnd})`,result:totals[i]};}schools.getCell('J'+totalRow).value={formula:`IF(B${totalRow}=0,"",C${totalRow}/B${totalRow})`,result:totals[0]?totals[1]/totals[0]:''};
 schools.autoFilter={from:'A6',to:'J'+dataEnd};schools.views=[{state:'frozen',ySplit:6,xSplit:1,showGridLines:false}];schools.pageSetup.printTitlesRow='1:6';schools.pageSetup.printArea=`A1:J${totalRow}`;
 for(let r=6;r<=totalRow;r++){const row=schools.getRow(r);row.eachCell({includeEmpty:true},(c,i)=>{c.font={name:'Arial',size:11,color:{argb:ink},bold:r===6||r===totalRow};c.alignment={wrapText:true,vertical:'middle',horizontal:i===1?'left':'center'};if(r===6||r===totalRow||r%2===1)c.fill={type:'pattern',pattern:'solid',fgColor:{argb:r===6?peach:r===totalRow?blue:cream}};if(i>1)c.numFmt=i===10?'0.0%':'#,##0';});if(r>6)row.height=38;}
 for(const [col,color] of [['D','E2F0E7'],['E','FFF0D5'],['F','FBE5E2'],['G','EFEDE9']])schools.addConditionalFormatting({ref:`${col}7:${col}${dataEnd}`,rules:[{type:'cellIs',operator:'greaterThan',formulae:[0],style:{fill:{type:'pattern',pattern:'solid',bgColor:{argb:color}}}}]});
 summary.columns=[{width:4},{width:32},{width:20},{width:4},{width:32},{width:20}];band(summary,'B2:F3',name);summary.mergeCells('B5:F5');summary.getCell('B5').value='Indicadores del registro escolar';summary.getCell('B5').font={size:14,bold:true,color:{argb:ink}};summary.getCell('B6').value='Fecha y hora (UTC)';summary.getCell('C6').value=date;summary.getCell('C6').numFmt='dd/mm/yyyy hh:mm';
 for(const [i,title,n] of [[0,'Alumnos registrados',9],[1,'Alumnos evaluados',12],[6,'Anteojos pendientes',15],[7,'Anteojos entregados',18]]){band(summary,`B${n}:E${n}`,title,peach);const cell=summary.getCell('F'+n);cell.value={formula:`Escuelas!${String.fromCharCode(66+i)}${totalRow}`,result:totals[i]};cell.numFmt='#,##0';cell.font={size:17,bold:true,color:{argb:ink}};cell.alignment={horizontal:'center',vertical:'middle'};summary.getRow(n).height=36;}
 band(summary,'B21:E21','Cobertura de registro',blue);summary.getCell('F21').value={formula:`IF(Escuelas!B${totalRow}=0,"",Escuelas!J${totalRow})`,result:totals[0]?totals[1]/totals[0]:''};summary.getCell('F21').numFmt='0.0%';summary.getCell('F21').alignment={horizontal:'center',vertical:'middle'};summary.getCell('F21').font={size:17,bold:true,color:{argb:ink}};summary.getRow(21).height=36;
 summary.mergeCells('B23:F24');summary.getCell('B23').value=rows.length?'La cobertura compara alumnos evaluados con alumnos registrados. Una celda de cobertura vacía significa que no hay alumnos registrados.':'Todavía no hay escuelas ni alumnos en este informe. Los ceros reflejan ausencia de registros.';summary.getCell('B23').alignment={wrapText:true,vertical:'middle'};summary.mergeCells('B26:F28');summary.getCell('B26').value='Fuente: registros actuales de la aplicación. Los estados corresponden al último tamizaje y las entregas a la receta vigente. No incluye nombres, DNI ni diagnósticos de alumnos. Consultá Escuelas para el detalle y Guía para interpretar cada indicador.';summary.getCell('B26').alignment={wrapText:true,vertical:'middle'};summary.getCell('B26').font={size:11,color:{argb:muted}};summary.pageSetup.printArea='B2:F28';
 guide.columns=[{width:29},{width:85}];band(guide,'A1:B2','Cómo leer el informe');guide.getRow(4).values=['Indicador','Qué significa'];guide.getRow(4).font={bold:true};INDICATORS.forEach(([a,b],i)=>{const row=guide.getRow(i+5);row.values=[a,b];row.height=48;row.alignment={wrapText:true,vertical:'middle'};row.getCell(1).font={bold:true,color:{argb:ink}};row.getCell(1).fill={type:'pattern',pattern:'solid',fgColor:{argb:cream}};});guide.mergeCells('A15:B17');guide.getCell('A15').value='Interpretación: los cuatro resultados del tamizaje suman los evaluados. No sumes órdenes pendientes y entregadas con los resultados visuales: describen etapas distintas. Este informe es una fotografía del registro, no una estimación de prevalencia ni un recuento de consultas realizadas.';guide.getCell('A15').alignment={wrapText:true,vertical:'middle'};guide.pageSetup.printArea='A1:B17';
 return Buffer.from(await wb.xlsx.writeBuffer());
}
